.TH VIMIV 1
.SH NAME
vimiv \- an image viewer with vim-like keybindings

.SH SYNOPSIS
.B vimiv
.RB [ \-bBfFhlLrRsSv ]
.RB [ \--start-from-desktop ]
.RB [ \--slideshow ]
.RB [ \--slideshow-delay
.IR SLIDESHOW-DELAY ]
.RB [ \-g,\ \--geometry
.IR GEOMETRY ]
.RB [ \--temp-basedir ]
.RB [ \--config
.IR FILE ]
.RB [ \--debug ]
.IR FILE[S]

.SH DESCRIPTION
Vimiv is an image viewer with vim-like keybindings. It is written in
python3 using the Gtk3 toolkit. Some of the features are:
.P
- Thumbnail mode
.P
- Simple library browser
.P
- Basic image editing
.P
- Command line with tab completion
.P
The complete documentation is not included in this manpage but is available at:
.P
https://github.com/karlch/vimiv/documentation/

.SH OPTIONS

.B "\-b, \--bar"
display the statusbar
.P
.B "\-f, \--fullscreen"
start in fullscreen
.P
.B "\-h, \--help"
display a simple help text
.P
.B "\-l, \--library"
display the library
.P
.B "\-r, \--recursive"
search the directory recursively for images
.P
.B "\-s, \--shuffle"
shuffle the filelist
.P
.B "\-v, \--version"
show version information and exit
.P
.B \--start-from-desktop
start using the desktop_start_dir as path
.P
.B \--slideshow
start in slideshow mode
.P
.BI "\--slideshow-delay " SLIDESHOW_DELAY
set the slideshow delay
.P
.BI "\-g, \--geometry " GEOMETRY
set the starting geometry
.P
.BI "\--temp-basedir"
use a temporary basedir
.P
.BI "\--config " FILE
use FILE as local configuration file instead of ~/.vimiv/vimivrc
.P
.BI "\--debug "
show GTK warnings at startup.
.P
All capitals negate the setting, so e.g. -B means do not display the statusbar.
For the long version prepend no-, e.g. --no-bar.

.SH BUGS
Probably. Please contact me under <karlch at protonmail dot com> or, even
better, open an issue on the github homepage.

.SH SEE ALSO
vimivrc(5)

.SH THANKS TO
James Campos, author of Pim https://github.com/Narrat/Pim upon which vimiv is
built.

Bert Muennich, author of sxiv https://github.com/muennich/sxiv which inspired
many of the features of vimiv.

Anyone who has contributed or reported bugs.

.SH RESOURCES
.B Website
https://karlch.github.io/vimiv/
.TP
.B Github
https://github.com/karlch/vimiv/
