.TH VIMIV 1 "May 2017" Linux vimiv
.SH NAME
.PP
vimiv \- an image viewer with vim\-like keybindings
.SH SYNOPSIS
.PP
\fB\fCvimiv\fR
[\fB\fC\-bBfFhlLrRsSv\fR]
[\fB\fC\-\-start\-from\-desktop\fR]
[\fB\fC\-\-slideshow\fR]
[\fB\fC\-\-slideshow\-delay\fR \fISLIDESHOW\-DELAY\fP]
[\fB\fC\-g\fR, \fB\fC\-\-geometry\fR \fIGEOMETRY\fP]
[\fB\fC\-\-temp\-basedir\fR]
[\fB\fC\-\-config\fR \fIFILE\fP]
[\fB\fC\-\-debug\fR]
[\fIFILE\fP]
\&...
.SH DESCRIPTION
.PP
Vimiv is an image viewer with vim\-like keybindings. It is written in
python3 using the Gtk3 toolkit. Some of the features are:
.RS
.IP \(bu 2
Thumbnail mode
.IP \(bu 2
Simple library browser
.IP \(bu 2
Basic image editing
.IP \(bu 2
Command line with tab completion
.RE
.PP
The complete documentation is not included in this manpage but is available at:
.PP
\[la]http://karlch.github.io/vimiv/documentation\[ra]
.SH OPTIONS
.TP
\fB\fC\-b\fR, \fB\fC\-\-bar\fR
display the statusbar
.TP
\fB\fC\-f\fR, \fB\fC\-\-fullscreen\fR
start in fullscreen
.TP
\fB\fC\-h\fR, \fB\fC\-\-help\fR
display a simple help text
.TP
\fB\fC\-l\fR, \fB\fC\-\-library\fR
display the library
.TP
\fB\fC\-r\fR, \fB\fC\-\-recursive\fR
search the directory recursively for images
.TP
\fB\fC\-s\fR, \fB\fC\-\-shuffle\fR
shuffle the filelist
.TP
\fB\fC\-v\fR, \fB\fC\-\-version\fR
show version information and exit
.TP
\fB\fC\-\-start\-from\-desktop\fR
start using the desktop_start_dir as path
.TP
\fB\fC\-\-slideshow\fR
start in slideshow mode
.TP
\fB\fC\-\-slideshow\-delay\fR \fISLIDESHOW_DELAY\fP
set the slideshow delay
.TP
\fB\fC\-g\fR, \fB\fC\-\-geometry\fR \fIGEOMETRY\fP
set the starting geometry
.TP
\fB\fC\-\-temp\-basedir\fR
use a temporary basedir
.TP
\fB\fC\-\-config\fR \fIFILE\fP
use FILE as local configuration file instead of
$XDG_CONFIG_HOME/vimiv/vimivrc and ~/.vimiv/vimivrc.
.TP
\fB\fC\-\-debug\fR
run in debug mode
.PP
All capitals negate the setting, so e.g. \-B means do not display the statusbar.
For the long version prepend no\-, e.g. \-\-no\-bar.
.SH BUGS
.PP
Probably. Please contact me under <karlch at protonmail dot com> or, even
better, open an issue on the github homepage.
.SH SEE ALSO
.PP
.BR vimivrc (5)
.SH THANKS TO
.PP
James Campos, author of Pim \[la]https://github.com/Narrat/Pim\[ra] upon which vimiv is
built.
.PP
Bert Muennich, author of sxiv \[la]https://github.com/muennich/sxiv\[ra] which inspired
many of the features of vimiv.
.PP
Anyone who has contributed or reported bugs.
.SH RESOURCES
.PP
\fBWebsite\fP
\[la]https://karlch.github.io/vimiv/\[ra]
.PP
\fBGithub\fP
\[la]https://github.com/karlch/vimiv/\[ra]
