.TH VIMIVRC 5
.SH NAME
vimivrc \- configuration files for the vimiv image viewer

.SH SYNOPSIS
/etc/vimiv/vimivrc, ~/.vimiv/vimivrc, /etc/vimiv/keys.conf, ~/.vimiv/keys.conf

.SH DESCRIPTION
Vimiv is configured via two files: basedir/vimivrc and basedir/keys.conf where
basedir is one of /etc/vimiv/ and ~/.vimiv/. The default configuration files are
installed to /etc/vimiv/. It is considered best-practice to copy them to
~/.vimiv/ and configure the copied files.
.TP
More information in a nicer format is available at:
.TP
http://karlch.github.io/vimiv/documentation/configuration/

.SH SETTINGS
Settings are configured in the vimivrc file. This file is separated into three
sections:
.TP
- GENERAL
.TP
- LIBRARY
.TP
- ALIASES
.TP
The first two sections configure settings, the third is used to define aliases.
.TP
What each setting means and what values are possible is explained below:
.TP
.B GENERAL
.TP
.TP
.BR start_fullscreen\ (Bool)
If yes, start in fullscreen mode.
.TP
.TP
.BR start_slideshow\ (Bool)
If yes, start in slideshow mode.
.TP
.TP
.BR slideshow_delay\ (Float)
Specify the delay for the slideshow.
.TP
.TP
.BR shuffle\ (Bool)
If yes, shuffle the images in the filelist randomly.
.TP
.TP
.BR display_bar\ (Bool)
If yes, show the statusbar at the bottom.
.TP
.TP
.BR thumbsize\ (Tuple)
Size for the thumbnails in the form of (x, y).
.TP
.TP
.BR thumb_maxsize\ (Tuple)
Maximum size for the thumbnails. This is the upper limit for zooming in on
thumbnails. Anything larger than (512, 512) is ignored.
.TP
.TP
.BR geometry\ (string)
A string of the form "WIDTHxHEIGHT" which sets the default size for the window.
Note that not all window managers respect this setting.
.TP
.TP
.BR recursive\ (Bool)
If yes,  search the given directory recursively for images at startup.
.TP
.TP
.BR rescale_svg\ (Bool)
If yes, rescale vector graphics automatically by reloading the image. Otherwise
simply zoom as if it were a normal image.
.TP
.TP
.BR overzoom\ (Bool)
If yes, scale images smaller than the current window size up to fit. Useful for
UHD displays, not good when viewing icons or other small images.
.TP
.TP
.BR search_case_sensitive\ (Bool)
If yes, search case sensitively, ignore case otherwise.
.TP
.TP
.BR incsearch\ (Bool)
If yes, search incrementally when typing.
.TP
.TP
.BR cache_thumbnails\ (Bool)
If yes, cache thumbnails saving them to ~/.vimiv/Thumbnails/.
.TP
.TP
.BR copy_to_primary\ (Bool)
If yes, copy to primary selection instead of clipboard.
.TP
.TP
.BR commandline_padding\ (Int)
Padding to use in the commandline and statusbar.
.TP
.TP
.BR completion_height\ (Int)
Height of the completion menu when showing command line completions.
.TP
.TP
.BR LIBRARY
.TP
.TP
.BR show_library\ (Bool)
If yes, always show library at start-up.
.TP
.TP
.BR library_width\ (Int)
Default width of the library when an image is open.
.TP
.TP
.BR expand_lib\ (Bool)
If yes, automatically expand the library to full window size if no image is open.
.TP
.TP
.BR border_width\ (Int)
Width of the border separating library and image.
.TP
.TP
.BR markup\ (String)
Markup used to highlight search results. This must be a correct markup opening
in the form of one <span ...> element as it gets closed with </span/>
.TP
.TP
.BR show_hidden\ (Bool)
If yes, show hidden files in the library and open hidden images.
.TP
.TP
.BR desktop_start_dir\ (String)
The directory in which vimiv should start if opened via the .desktop file.
.TP
.TP
.BR file_check_amount\ (Int)
The amount of files vimiv should check in a directory for whether they are
images or not. This affects the size column of directories in the library. As
soon as this number is reached, checks are stopped and a + is appended, e.g.
30+. A higher number increases precision and information at the cost of speed.
.TP
.TP
.BR ALIASES
.TP
It is possible to configure aliases for the command line in this section.
.TP
An alias is defined in the form of: aliasname: command.

.SH KEYBINDINGS
Keybindings are configured in the keys.conf file. Similar to the vimivrc this
file is split up into sections:
.TP
.BR GENERAL:
keybindings defined here apply in image and thumbnail mode as well as the library.
.TP
.BR IM_THUMB:
keybindings defined here apply in image and thumbnail mode.
.TP
.BR IM_LIB:
keybindings defined here apply in image mode and in the library.
.TP
.BR IMAGE:
keybindings defined here only apply in image mode.
.TP
.BR THUMBNAIL:
keybindings defined here only apply in thumbnail mode. Note: empty by default.
.TP
.BR LIBRARY:
keybindings defined here only apply in the library.
.TP
.BR MANIPULATE:
keybindings defined here only apply in manipulate mode.
.TP
.BR COMMAND:
keybindings defined here only apply in the command line.
.TP
Keybindings are defined in the form of keyname: command [arguments]
.TP
Supported\ modifiers:
Shift via Shift+keyname, Control via ^keyname, Alt via Alt+keyname.
.TP
command [arguments] has to be a valid vimiv command with correct arguments.

.SH COMMANDS

.TP
.TP
.BR accept_changes
Accept changes made in manipulate.
.TP
.BR alias
Add an alias for a command.
.TP
.BR autorotate
Rotate all images in the current filelist according to exif data.
.TP
.BR center
Scroll to the center of the image.
.TP
.BR clear_thumbs
Delete all files in the thumbnail directory.
.TP
.BR clear_trash
Delete all files in the trash directory.
.TP
.BR copy_abspath
Copy the absolute path of the currently selected file to the clipboard.
.TP
.BR copy_basename
Copy the base name of the currently selected file to the clipboard.
.TP
.BR delete
Delete the current image.
.TP
.BR discard_changes
Discard any changes made in manipulate mode and leave it.
.TP
.BR first
Move to the first image of the filelist in image/thumbnail mode.
.TP
.BR first_lib
Move to the first file of the filelist in the library.
.TP
.BR fit
Fit the image to the current window size..
.TP
.BR fit_horiz
Fit the image horizontally to the current window size.
.TP
.BR fit_vert
Fit the image vertically to the current window size.
.TP
.BR flip
Flip the current image.
.TP
.BR focus_library
Focus the library.
.TP
.BR format
Format all currently open filenames.
.TP
.BR fullscreen
Toggle fullscreen mode.
.TP
.BR grow_lib
Increase the library width.
.TP
.BR last
Move to the last image of the filelist in image/thumbnail mode.
.TP
.BR last_lib
Move to the last file of the filelist in the library.
.TP
.BR library
Toggle the library.
.TP
.BR manipulate
Enter manipulate mode.
.TP
.BR mark
Mark the currently selected image.
.TP
.BR mark_all
Mark all images in the current filelist.
.TP
.BR mark_between
Mark all images between the last two marked images.
.TP
.BR mark_toggle
Toggle the current
.TP
.BR move_up
Move up one directory in the library.
.TP
.BR next
Move to the next image in the filelist of image mode.
.TP
.BR next!
Force moving to the next image in the filelist of image mode.
.TP
.BR prev
Move to the previous image in the filelist of image mode.
.TP
.BR prev!
Force moving to the previous image in the filelist of image mode.
.TP
.BR q
Quit vimiv.
.TP
.BR q!
Force quitting vimiv.
.TP
.BR reload_lib
Reload the library.
.TP
.BR rotate
Rotate the image counter-clockwise.
.TP
.BR set\ animation!
Toggle the animation status of animated Gifs.
.TP
.BR set\ brightness
Set the brightness of the current image.
.TP
.BR set\ clipboard!
Toggle the copy_to_primary setting.
.TP
.BR set\ contrast
Set the contrast of the current image.
.TP
.BR set\ library_width
Set the library width.
.TP
.BR set\ overzoom!
Toggle the overzoom setting.
.TP
.BR set\ rescale_svg!
Toggle the rescale_svg setting.
.TP
.BR set\ sharpness
Set the sharpness of the current image.
.TP
.BR set\ show_hidden!
Toggle the show_hidden setting.
.TP
.BR set\ slideshow_delay
Set the slideshow delay.
.TP
.BR set\ statusbar!
Toggle the statusbar.
.TP
.BR shrink_lib
Decrease the library width.
.TP
.BR slideshow
Toggle the slideshow.
.TP
.BR slideshow_delay
Change the value of the slideshow delay.
.TP
.BR tag_write
Write the names of all currently marked images to a tagfile.
.TP
.BR tag_load
Load all images in a tagfile into image mode.
.TP
.BR tag_remove
Delete a tagfile.
.TP
.BR thumbnail
Toggle thumbnail mode.
.TP
.BR unfocus_library
Focus the widget last focused before the library.
.TP
.BR version
Display pop-up with version information.
.TP
.BR zoom_in
Zoom in.
.TP
.BR zoom_out
Zoom out.
.TP
.BR zoom_to
Zoom image to a given percentage.

.SH KEY-COMMANDS
The following commands can only be bound to keys and are not accessible from the
command line.
.TP
.TP
.BR clear_status
Clear any numbers or messages from the statusbar.
.TP
.BR command
Enter the command line.
.TP
.BR scroll
Scroll image or thumbnail.
.TP
.BR scroll_lib
Scroll the library.
.TP
.BR search
Search for text in the current filelist.
.TP
.BR search_next
Navigate to the next search result.
.TP
.BR search_next
Navigate to the previous search result.
.TP
.BR history_down
Go down by one in command history.
.TP
.BR history_up
Go up by one in command history.
.TP
.BR discard_command
Leave the command line discarding currently entered text.
.TP
.BR complete
Start command line completion.
.TP
.BR complete_inverse
Start command line completion selecting items inversely.
.TP
.BR slider
Change the value of the currently focused slider.
.TP
.BR focus_slider
Focus one of the manipulate sliders.

.SH SEE ALSO
vimiv(1), date(1)
