.TH VIMIV 1
.SH NAME
vimiv \- an image viewer with vim-like keybindings

.SH SYNOPSIS
.B vimiv
.RB [ \-bBfFhlLrRsS ]
.RB [ \-g,\ \-\-geometry
.IR GEOMETRY ]
.RB [ \--slideshow ]
.RB [ \--slideshow-delay
.IR SLIDESHOW-DELAY ]
.IR FILE[S]

.SH DESCRIPTION
Vimiv is an image viewer with vim-like keybindings for X. It is written in
python and works well with tiling window managers.
.P
Vimiv features two different modes of operation: image and thumbnail mode.
Additionally one can open a library and a manipulation toolbar. If a file is
passed to vimiv it starts in image mode, otherwise a quick error is displayed
and the library appears.
.P
In image mode the current image and possibly a statusbar is shown. One can
navigate through the images and apply basic actions.
.P
In thumbnail mode a grid of small previews and the name of each image is
displayed. It is useful for getting an overview of the open images and for
selecting a specific one.
.P
The library can be displayed at the left of the window. Basically it is a list
of the current images. One can select any image or navigate the directory tree
to load new images.
.P
The manipulate toolbar can be displayed just above the statusbar and adds a few
more editing options. These feature the change of brightness, contrast and
sharpness of the image and a button called "optimize". This button uses
imagemagick to optimize contrast, gamma and level of the image. This tends to
work well with photographs.

.SH OPTIONS
.TP
.B \-b
display the statusbar
.TP
.B \-f
start in fullscreen
.TP
.B \-h
display a simple help text
.TP
.B \-l
display the library
.TP
.B \-r
search the directory recursively for images
.TP
.B \-s
shuffle the filelist
.TP
.B \--slideshow
start in slideshow mode
.TP
.BI "\--slideshow-delay " SLIDESHOW_DELAY
set the slideshow delay
.TP
.BI "\-g " GEOMETRY
set the starting geometry
.TP
.BI "\--geometry " GEOMETRY
same as \-g
.TP
All capitals negate the setting, so e.g. -B means do not display the statusbar.

.SH KEYBOARD COMMANDS
General keyboard commands that always apply.
.TP
.BR 0 \- 9
Prefix the next command with a COUNT. If this is possible for a command it is
denoted.
.TP
.BR f
Toggle fullscreen.
.TP
.BR b
Toggle the statusbar.
.TP
.BR q
Quit vimiv.

.SH MAIN KEYBOARD COMMANDS
These keyboard commands apply when the image is focused and in thumbnail mode.
.TP
.BR g
Focus the first image or image number [COUNT].
.TP
.BR G
Focus the last image or image number [COUNT].
.TP
.BR m
Mark the current image, marked images will be printed to stdout on exit.
.TP
.BR M
Toggle the mark status. If images are marked, all marks will be removed,
otherwise the last list of marked images will be marked again.
.TP
.BR t
Toggle thumbnail mode.
.TP
.BR o
Toggle library.
.TP
.BR u
Open library and move up a directory.
.TP
.BR O
Focus the library.
.TP
.BR >
Rotate image clockwise.
.TP
.BR <
Rotate image counter-clockwise.
.TP
.BR y
Flip image horizontally.
.TP
.BR Y
Flip image vertically.
.TP
.BR x
Delete image, this moves the file to "~/.vimiv/Trash".

.SH IMAGE KEYBOARD COMMANDS
These keyboard commands apply when the image is focused.
.TP
.BR h
Scroll to the left.
.TP
.BR j
Scroll down.
.TP
.BR k
Scroll up.
.TP
.BR l
Scroll to the right.
.TP
.BR H
Scroll to the left end.
.TP
.BR J
Scroll to the bottom.
.TP
.BR K
Scroll to the top.
.TP
.BR L
Scroll to the right end.
.TP
.BR n
Focus the [COUNT] next image in filelist.
.TP
.BR p
Focus the [COUNT] previous image in filelist.
.TP
.BR +
Zoom in.
.TP
.BR -
Zoom out.
.TP
.BR w
Fit the image to the current window size or zoom to [COUNT]. If [COUNT] begins
with 0 zoom to 1/[COUNT].
.TP
.BR W
Center the current image.
.TP
.BR e
Fit the image to the current window size horizontally.
.TP
.BR E
Fit the image to the current window size vertically.
.TP
.BR r
Toggle the rescaling of vector graphics.
.TP
.BR s
Toggle the slideshow. If prefixed by [COUNT] set the slideshow delay to [COUNT]
.TP
.BR ,
Decrease slideshow delay by 0.2
.TP
.BR .
Increase slideshow delay by 0.2
.TP
.BR space
Toggle animation state of animated images (e.g. Gifs).
.TP
.BR c
Open manipulation toolbar.

.SH KEYBOARD COMMANDS IN THUMBNAIL MODE
.TP
.BR h
Focus [COUNT] images left.
.TP
.BR j
Focus [COUNT] images down.
.TP
.BR k
Focus [COUNT] images up.
.TP
.BR l
Focus [COUNT] right.
.TP
.BR space
Select the current image and return to image mode.
.TP
.BR return
Select the current image and return to image mode.

.SH KEYBOARD COMMANDS IN THE LIBRARY
.TP
.BR h
Move up a directory.
.TP
.BR j
Focus [COUNT] down.
.TP
.BR k
Focus [COUNT] up.
.TP
.BR l
Select the current path. If it is an image show it first, if selected again open
the image and close the library.
.TP
.BR g
Focus the first image or image number [COUNT].
.TP
.BR G
Focus the last image or image number [COUNT].
.TP
.BR H
Decrease the library size.
.TP
.BR L
Increase the library size.
.TP
.BR u
Move up a directory.
.TP
.BR i
Focus the cmd_handler.
.TP
.BR Escape
Unfocus the cmd_handler.
.TP
.BR O
Focus the image.
.TP
.BR ^k
Go up in history of the cmd_handler.
.TP
.BR ^j
Go down in history of the cmd_handler.
.TP
.BR o
Toggle status of the library.
.TP
.BR space
Select the current path. If it is an image open it and close the library.
.TP
.BR return
Select the current path. If it is an image open it and close the library.

.SH KEYBOARD COMMANDS IN THE MANIPULATION BAR
.TP
.BR b
Focus the brightness slider.
.TP
.BR c
Focus the contrast slider.
.TP
.BR s
Focus the sharpness slider.
.TP
.BR h
Decrease slider value by 1 or by [COUNT].
.TP
.BR l
Increase slider value by 1 or by [COUNT].
.TP
.BR H
Decrease slider value by 10 or by [COUNT].
.TP
.BR L
Increase slider value by 10 or by [COUNT].
.TP
.BR o
Optimize the image.
.TP
.BR Escape
Cancel changes and close the manipulation bar.
.TP
.BR Return
Accept changes and close the manipulation bar.

.SH CONFIGURATION
All keyboard commands and some additional settings can be configured in
"/etc/vimivrc.py" or in "~/.vimiv/vimivrc.py" (recommended). This file is python
code which declares variables used in the actual program. Since python code is
very readable this should not be an issue. The following settings can be
configured:

.TP
.BR start_fullscreen\ (Bool)
If True start in fullscreen mode.
.TP
.BR start_slideshow\ (Bool)
If True start in slideshow mode.
.TP
.BR slideshow_delay\ (Float)
Specify the delay in slideshow mode.
.TP
.BR shuffle\ (Bool)
If True shuffle the images in filelist.
.TP
.BR display_bar\ (Bool)
If True show the statusbar.
.TP
.BR thumbsize\ (tuple)
Size for the thumbnails.
.TP
.BR geometry\ (string)
A string of the form "WIDTHxHEIGHT" which sets the default size for the image.
.TP
.BR recursive\ (Bool)
If True search the given directory recursively for images.
.TP
.BR rescale_svg\ (Bool)
If True rescale vector graphics automatically by reloading the image. Otherwise
simply zoom as if it were a normal image.
.TP
.BR show_library\ (Bool)
If True show the library at startup.
.TP
.BR library_width\ (Int)
The default width of the library.
.TP
.BR expand_lib\ (Bool)
If True automatically expand the library to full window size if now image is
open.
.TP
.BR border_width\ (Int)
Width of the border separating library and image.
.TP
.BR border_color\ (String)
Color of the border separating library and image, must be given in the form
"#XXYYZZ".

.SH THUMBNAIL CACHING
Thumbnails are cached under "~/.vimiv/Thumbnails" so they can be loaded a lot
faster.

.SH IMAGE MANIPULATION
The basic manipulations (rotate, flip, ...) are automatically also applied to
the file. The file is overwritten. The more advanced manipulations which can be
accessed in the manipulation toolbar are only written to the actual file if one
selects "Accept", otherwise they are ignored. For the "optimize" button
imagemagick must be installed.

.SH LIBRARY VIEWER
Users of "ranger" should be familiar with the concept. This library viewer will
only show files which it recognizes as images and directories as vimiv can and
should not access other files. If an image is selected vimiv will populate a new
filelist with all images in the same directory, close the library viewer  and
focus the selected image. If a directory is selected, all accessible files in
that directory will be shown in the library.

Additionally there is a small text entry at the bottom. This is called the
cmd_handler. One can type the absolute or relative path of an image/directory
and this path will be focused. If one only types a string this string will be
searched for in all files in the current directory. If it is a substring of a
filename that file will be focused. Consider e.g. the case where the files
"image_001", "image_002" and "image_003" are in current directory. If one enters
"3", "image_003" will be focused.

If the input is prepended with "!" the following string will be sent to the
shell and executed. Here "%" is substituted with the currently selected file and
"*" is substituted with all files in the current directory. So if "image" is
selected and one enters "!gimp %", "image" will be opened in gimp.

The cmd_handler remembers entered commands during one session. This is mainly
done so one can quickly edit typos.

.SH MARKING
If images are marked the simple manipulations (rotating, flipping and deleting)
are executed for all marked images and not for the current image. In thumbnail
mode those actions will always work on marked images. If there are none, no
manipulation will be done.

.SH BUGS
Probably. Please contact me under <christian dot karl at protonmail dot com>.

.SH THANKS TO
James Campos, author of Pim https://github.com/Narrat/Pim upon which vimiv is
built.

Bert Muennich, author of sxiv https://github.com/muennich/sxiv which inspired
many of the features of vimiv.

.SH HOMEPAGE
https://github.com/karlch/vimiv
