#!/usr/bin/env python3
# encoding: utf-8
"""Vimiv executable."""
import signal
import sys
from vimiv.app import Vimiv

if __name__ == '__main__':
    signal.signal(signal.SIGINT, signal.SIG_DFL)  # ^C
    Vimiv().run(sys.argv)
